language: java
env:
  - ISABELLE_VERSION=2015 SCALA_VERSION=2.11.8 PROFILE=quick
  - ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8 PROFILE=quick
install:
  - git submodule update --init --recursive
os:
  - osx
script:
  - ./.ci/travis.sh
matrix:
  include:
    - env: ISABELLE_VERSION=2015 SCALA_VERSION=2.10.6 PROFILE=quick
      os: linux
      jdk: oraclejdk7
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8 PROFILE=slow
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.isabelle
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
