language: java
env:
  - ISABELLE_VERSION=2015 SCALA_VERSION=2.11.8
  - ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8
install:
  - git submodule update --init --recursive
os:
  - osx
script:
  - ./sbt "++$SCALA_VERSION" compile
  - ./sbt "++$SCALA_VERSION" "cli/run --version $ISABELLE_VERSION build"
  - ./sbt "++$SCALA_VERSION" test
matrix:
  include:
    - env: ISABELLE_VERSION=2015 SCALA_VERSION=2.10.6
      os: linux
      jdk: oraclejdk7
    - env: ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8
      os: linux
      jdk: oraclejdk8
