language: java
env:
  matrix:
    - ISABELLE_VERSION=stable:2017 SCALA_VERSION=2.11.12 PROFILE=quick
    - ISABELLE_VERSION=stable:2018-RC0 SCALA_VERSION=2.11.12 PROFILE=quick
os:
  - osx
script:
  - ./.ci/travis.sh
deploy:
  - provider: script
    script: ./.ci/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      condition: $DEPLOY = 1
  - provider: bintray
    file: .ci/bintray
    user: larsrh
    skip_cleanup: true
    on:
      branch: master
      condition: $DEPLOY = 1
    key:
      secure: "eTZ3R7NVfCqqolU+DG4TR5CJBp0YT/k1dSjRwLMrGyypZvlzsE3Ur3VMLWYH39pypHA9ayDCKNJlqM3kQzXxCC3kGRgk7u7cqM5HwgT/l54Jzz7S731SPmSdIaGDbycAzz6bauYvu1v2jDrsSuS6bo8mfzH4HLSz86qfK8bpZdk="
matrix:
  include:
    - env: ISABELLE_VERSION=stable:2016 SCALA_VERSION=2.11.12 PROFILE=generic
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=stable:2016-1 SCALA_VERSION=2.11.12 PROFILE=generic
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=stable:2017 SCALA_VERSION=2.12.4 PROFILE=slow
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=stable:2017 SCALA_VERSION=2.12.4 PROFILE=slow
      os: linux
      jdk: oraclejdk9
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=stable:2018-RC0 SCALA_VERSION=2.12.4 PROFILE=slow
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=devel:isabelle-mirror SCALA_VERSION=2.12.4 PROFILE=devel
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.local/share/libisabelle/user
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  - rm -rf $HOME/.local/share/libisabelle/devel
