install:
  - cinst sbt
  - cmd: SET PATH=%PATH%;"C:\Program Files (x86)\sbt\bin"
  - cmd: git submodule update --init --recursive
platform:
  - x86
  - x64
environment:
  matrix:
    - ISABELLE_VERSION: 2016
build_script:
  - sbt compile
test_script:
  - sbt "cli/run --version %ISABELLE_VERSION% build"
